// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RedisDestination
func (this *RedisDestination) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisDestination
func (this *RedisDestination) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Auth
func (this *Auth) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Auth
func (this *Auth) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SecretReference
func (this *SecretReference) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SecretReference
func (this *SecretReference) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PlainAuth
func (this *PlainAuth) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PlainAuth
func (this *PlainAuth) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisSettings
func (this *RedisSettings) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisSettings
func (this *RedisSettings) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TrafficPolicy
func (this *TrafficPolicy) MarshalJSON() ([]byte, error) {
	str, err := RedisdestinationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TrafficPolicy
func (this *TrafficPolicy) UnmarshalJSON(b []byte) error {
	return RedisdestinationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RedisdestinationMarshaler   = &jsonpb.Marshaler{}
	RedisdestinationUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
