// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RedisService
func (this *RedisService) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService
func (this *RedisService) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Settings
func (this *RedisService_Settings) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Settings
func (this *RedisService_Settings) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_KeyMatch
func (this *RedisService_KeyMatch) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_KeyMatch
func (this *RedisService_KeyMatch) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_RouteMatch
func (this *RedisService_RouteMatch) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_RouteMatch
func (this *RedisService_RouteMatch) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Destination
func (this *RedisService_Destination) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Destination
func (this *RedisService_Destination) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Mirror
func (this *RedisService_Mirror) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Mirror
func (this *RedisService_Mirror) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Route
func (this *RedisService_Route) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Route
func (this *RedisService_Route) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Percent
func (this *Percent) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Percent
func (this *Percent) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Fault
func (this *Fault) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Fault
func (this *Fault) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RedisserviceMarshaler   = &jsonpb.Marshaler{}
	RedisserviceUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
