// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using ApplicationProtocol within kubernetes types, where deepcopy-gen is used.
func (in *ApplicationProtocol) DeepCopyInto(out *ApplicationProtocol) {
	p := proto.Clone(in).(*ApplicationProtocol)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProtocol. Required by controller-gen.
func (in *ApplicationProtocol) DeepCopy() *ApplicationProtocol {
	if in == nil {
		return nil
	}
	out := new(ApplicationProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProtocol. Required by controller-gen.
func (in *ApplicationProtocol) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
