// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: metaprotocol/v1alpha1/metaprotocol_application_protocol.proto

//import "google/api/field_behavior.proto";

// $schema: metaprotocol.aeraki.io.v1alpha1.ApplicationProtocol
// $title: Application Protocol
// $description: ApplicationProtocol defines an application protocol built on top of MetaProtocol.
//
// ApplicationProtocol defines an application protocol built on top of MetaProtocol.
//
// ```yaml
// apiVersion: metaprotocol.aeraki.io/v1alpha1
// kind: ApplicationProtocol
// metadata:
//   name: dubbo
//   namespace: istio-system
// spec:
//   protocol: dubbo
//   codec: aeraki.meta_protocol.codec.dubbo
// ```

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplicationProtocol defines an application protocol built on top of MetaProtocol.
//
// <!-- crd generation tags
// +cue-gen:ApplicationProtocol:groupName:metaprotocol.aeraki.io
// +cue-gen:ApplicationProtocol:version:v1alpha1
// +cue-gen:ApplicationProtocol:storageVersion
// +cue-gen:ApplicationProtocol:annotations:helm.sh/resource-policy=keep
// +cue-gen:ApplicationProtocol:labels:app=aeraki,chart=aeraki,heritage=Tiller,release=aeraki
// +cue-gen:ApplicationProtocol:subresource:status
// +cue-gen:ApplicationProtocol:scope:Cluster
// +cue-gen:ApplicationProtocol:resource:categories=aeraki-io,metaprotocol-aeraki-io
// +cue-gen:ApplicationProtocol:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=metaprotocol.aeraki.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type ApplicationProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Codec    string `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
}

func (x *ApplicationProtocol) Reset() {
	*x = ApplicationProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationProtocol) ProtoMessage() {}

func (x *ApplicationProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationProtocol.ProtoReflect.Descriptor instead.
func (*ApplicationProtocol) Descriptor() ([]byte, []int) {
	return file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationProtocol) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ApplicationProtocol) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

var File_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto protoreflect.FileDescriptor

var file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1f, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x65,
	0x72, 0x61, 0x6b, 0x69, 0x2e, 0x69, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x22, 0x47, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x65, 0x72, 0x61, 0x6b, 0x69, 0x2d, 0x6d,
	0x65, 0x73, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescOnce sync.Once
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescData = file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDesc
)

func file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescGZIP() []byte {
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescOnce.Do(func() {
		file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescData)
	})
	return file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDescData
}

var file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_goTypes = []interface{}{
	(*ApplicationProtocol)(nil), // 0: metaprotocol.aeraki.io.v1alpha1.ApplicationProtocol
}
var file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_init() }
func file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_init() {
	if File_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_goTypes,
		DependencyIndexes: file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_depIdxs,
		MessageInfos:      file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_msgTypes,
	}.Build()
	File_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto = out.File
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_rawDesc = nil
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_goTypes = nil
	file_metaprotocol_v1alpha1_metaprotocol_application_protocol_proto_depIdxs = nil
}
