// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ApplicationProtocol
func (this *ApplicationProtocol) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolApplicationProtocolMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ApplicationProtocol
func (this *ApplicationProtocol) UnmarshalJSON(b []byte) error {
	return MetaprotocolApplicationProtocolUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	MetaprotocolApplicationProtocolMarshaler   = &jsonpb.Marshaler{}
	MetaprotocolApplicationProtocolUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
