// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for MetaRouter
func (this *MetaRouter) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MetaRouter
func (this *MetaRouter) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MetaRoute
func (this *MetaRoute) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MetaRoute
func (this *MetaRoute) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KeyValue
func (this *KeyValue) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KeyValue
func (this *KeyValue) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MetaRouteMatch
func (this *MetaRouteMatch) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MetaRouteMatch
func (this *MetaRouteMatch) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StringMatch
func (this *StringMatch) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StringMatch
func (this *StringMatch) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MetaRouteDestination
func (this *MetaRouteDestination) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MetaRouteDestination
func (this *MetaRouteDestination) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Destination
func (this *Destination) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Destination
func (this *Destination) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PortSelector
func (this *PortSelector) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PortSelector
func (this *PortSelector) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LocalRateLimit
func (this *LocalRateLimit) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LocalRateLimit
func (this *LocalRateLimit) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LocalRateLimit_TokenBucket
func (this *LocalRateLimit_TokenBucket) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LocalRateLimit_TokenBucket
func (this *LocalRateLimit_TokenBucket) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LocalRateLimit_Condition
func (this *LocalRateLimit_Condition) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LocalRateLimit_Condition
func (this *LocalRateLimit_Condition) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GlobalRateLimit
func (this *GlobalRateLimit) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GlobalRateLimit
func (this *GlobalRateLimit) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GlobalRateLimit_Descriptor
func (this *GlobalRateLimit_Descriptor) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GlobalRateLimit_Descriptor
func (this *GlobalRateLimit_Descriptor) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Percent
func (this *Percent) MarshalJSON() ([]byte, error) {
	str, err := MetaprotocolMetarouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Percent
func (this *Percent) UnmarshalJSON(b []byte) error {
	return MetaprotocolMetarouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	MetaprotocolMetarouterMarshaler   = &jsonpb.Marshaler{}
	MetaprotocolMetarouterUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
